# Named Entit recognition

In [1]:
import spacy
from nltk import sent_tokenize

In [2]:
!python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 5.1 MB/s  0:01:44[0m eta 0:00:01[36m0:00:03
Requirement already satisfied: spacy-curated-transformers<1.0.0,>=0.2.2 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from en-core-web-trf==3.8.0) (0.3.1)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.5.1+cu121)
Requirement already satisfied: regex>=2022 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2026.7.19)
Requirement already satisfied: filelock in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.29.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.15.0)
Requirement already satisfied: networkx in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.4.2)
Requirement already satisfied: jinja2 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.6)
Requirement already satisfied: fsspec in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.9.86)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from sympy==1.13.1->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.1.5)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')

# Load model

In [3]:
def load_model():
    nlp = spacy.load("en_core_web_trf")
    return nlp

In [4]:
nlp_model = load_model()

/home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/keshtech/miniconda3/envs/nlp_series/lib/python3.10/site-packages/thinc/shims/pytorch.py:253: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(filelike, map_location=device))

# load Dataset

In [5]:
import os 
import sys
import pathlib
folder_path = pathlib.Path().parent.resolve()
sys.path.append(os.path.join(folder_path, '../'))
from utils import load_subtitles_dataset

In [6]:
dataset_path = "../data/Subtitles/"
df = load_subtitles_dataset(dataset_path)

In [7]:
df.head()

   episode                                             script
0      118  Connecting old words that have been used up\n ...
1      112  Connecting old words that have been used up\n ...
2       24  C'mon!\n Running like a fugitive,\n Being chas...
3      148  Hey boys, listen up!\n Humans aren’t such a bi...
4      123  Connecting old words that have been used up\n ...

In [8]:
sample_script = df.iloc[0]['script']
sample_script

"Connecting old words that have been used up\n I just want to convey my simple thoughts\n That day's faint wind blows away\n at the castle ruins of yesterday\n I'll laugh with you and live for the moment\n Still that incident will continue to trouble you, right?\n That's why it must be good-bye\n Leaving nothing behind, let us share what is left\n In time, we'll realize that it was everything\n And sadness will touch our cheeks, creating a river of tears\n Trembling thoughts swept into a vortex and melting away\n Hurry!\n Right…\n We’re close!\n There are two enemies left…\n There are three of us… lt’s three against two.\n We might be able to do it with one more contact if we do it well.\n All right! All right! Let’s do it!\n No! It’s four against two!\n Okay, okay! I’m sorry.\n Counting Akamaru, it’s four against two!\n Let’s finish it quickly with our new technique next!\n Say, say. If necessary, I’ll do an awesome Shadow Clone,\n so it’ll be okay!\n That’s reassuring…\n But my strategy comes first. Got it?\n Y-Yeah…\n For that purpose,\n we have to catch up before the sun sets at any cost.\n I know. Full throttle!\n The sun’s starting to set…\n Neither Jirobo nor Kidomaru have come.\n It seems they’re having a hard time.\n It doesn’t matter… More important is Lord Orochimaru.\n We’ve only completed one-third of the journey in half a day…\n They all have Curse Marks, huh…\n No questions asked, huh?\n This is gonna be different than that time before\n with your surprise attack…\n Too much interference…\n Yeah, this is bad…\n We don’t know whether we’ll make it in time at this rate!\n Damn! We still can’t catch up…\n No, this is good enough.\n We’ll maintain this distance and continue the pursuit…\n Wh-What do you mean?\n I mean, we’re delaying the attack until dawn breaks.\n Get real! We can’t afford such leisure !\n That’s right! Besides, if we’re going to attack anyway,\n isn’t it more advantageous to use the darkness and attack?!\n For us, the darkness works to our advantage\n only the moment we launch the attack.\n It’d be close to impossible to grab Sasuke,\n get away from them and escape to a safe location\n in just that one moment.\n If we couldn’t get Sasuke back in that one moment,\n they’d probably just focus on guarding the coffin.\n If that happens, we wouldn’t stand a chance in the darkness.\n On the contrary,\n for the part where they wouldn’t have to move needlessly,\n suddenly they’d get the advantage.\n It’d be a different story if we had Neji’s Byakugan, but…\n Hey, come on.\n Aren’t you forgetting Akamaru’s nose and mine as well??\n I was sure to include your senses of smell in the calculations!\n Even so, up ahead they have the geographical advantage.\n Plus…\n if I can’t use my Jutsu, it’ll be no use.\n Even if I seal off their movements with Shadow Possession Jutsu…\n the effect would be reduced to half if clouds were to cover the moon.\n It’s a drag, but there are too many dangers, and uncertain elements.\n But!\n Got it!\n Naruto?\n You’re the leader…\n I’ll follow your instructions, Shikamaru!\n Right. I’m counting on you!\n The Vessel Arrives Too Late\n Hey, Tayuya! Will we really make it in time?\n I was just told to deliver Master Sasuke by tomorrow.\n By tomorrow, huh?\n I can’t say that we have lots of time to spare,\n but I guess we’ll make it in time.\n I hope so.\n Lord Orochimaru…\n Sasuke…\n No Sasuke…yet?\n He’s running out of time… He can’t go on any longer.\n Lord Orochimaru…\n Several bodies have been prepared for you!\n And…you could even use me, if necessary…\n It has to be Sasuke…\n How long do you think I’ve waited?\n It’s a matter of urgency!\n The Third Hokage’s Jutsu…\n His curse was stronger than expected!\n Take this! Sealing Jutsu! Reaper Death Seal!\n Wh-What’s this sensation?\n Seal!\n My arm…\n If you don’t “reanimate” right now, you’ll lose everything!\n Is that what you want?!\n Lose everything…\n I’ve selected and prepared proficient bodies for you.\n Please leave it to me! Also…\n I’ll handle the recovery of Sasuke as well.\n Shall I use Kimimaro?\n Curse you …\n Third Hokage!\n Release!\n Listen well, everyone!\n I shall release you from this prison…\n However, it’ll only be one of you!\n Now all that’s left is to wake up Kimimaro, huh?\n Just as I thought…\n I wasn’t summoned this time, either.\n Dr. Kabuto, I…\n Take care of your body.\n Your role is now finished.\n It’s not Sound Ninja Five now, Kimimaro…\n I…still haven’t…\n Your replacement has already been found.\n He possesses power equal to your “Earth” Curse Mark.\n He has been given the “Heaven” Curse Mark.\n Additionally, he even has the Kekkei Genkai.\n Wonder who’s stronger…\n What’s the matter? Don’t get too excited.\n Dr. Kabuto…\n M-My life, how much do I have left?\n You shouldn’t talk anymore…\n P-People… People are born with some kind of meaning…\n Since people are born,\n there must be some kind of important calling.\n Recently I’ve started thinking so…\n That the meaning for being born…\n For people, finding the meaning is…\n the only freedom God has given.\n I understand what you want to say.\n Indeed, Lord Orochimaru is now suffering.\n It’s an unprecedented difficult situation,\n but I’ll mince no words.\n What can you do now?\n You’ve now lost your value as a “vessel.”\n A new vessel is heading this way.\n Well…\n At this point in time, it’s too late, but…\n Okay! You said you were going to let one person out of here.\n You’re going to keep your promise.\n What’re you doing? Open the door now!\n What? There was another one?\n Hurry up and…\n No…I… I’ll be eaten here, right now…\n I’ll let you out of here…\n And I shall grant you just one wish.\n My clan that was captured for your experiments.\n Please release them.\n Sure. Consider it done.\n You don’t have to worry.\n Your strong will is going to remain as Residual Aura inside me.\n It’s not like you’ll lose everything.\n Now then, your flesh is mine…\n With this, Lord Orochimaru’s body will, once again\n be unable to reanimate for several years.\n However, there is the next time.\n I-Indeed…\n my body no longer has value as a vessel for Reanimation Jutsu.\n It will now be difficult for me who has lost everything…\n to find my own calling.\n I’ve finally understood that…\n Even if it’s not me,\n I’ll bring in the new “vessel” even if it costs me my life.\n That’s my repayment to Lord Orochimaru…\n That’s the only redemption for me for being worthless…\n Hold on a minute!\n Are we almost there?\n No… It should still take a while.\n More importantly…\n What were those idiots Jirobo and Kidomaru doing?!\n We caught up!\n All right! I’ll take care of this nice and quick!\n R-Right away?!\n Eat this!\n Multiple Fists Barrage!\n Chakra in his palm…?!\n Shadow Clone Transformation, eh?\n Rasengan!\n N-No way… His hands now…?!\n There’s no point if I catch you before you do it!\n Now, Kiba!\n Tunneling Fang!\n This was also a Shadow Clone?!\n Luring Sakon into alignment with me…\n and aiming at me from the start?!\n You think you succeeded just with that?!\n Damn!\n I’ve been nailed.\n Shadow Possession Jutsu succeeded!\n A diversion…\n He’s coming!\n Tayuya! What’re you doing idling away?!\n N-No!\n Why do you move forward?!\n I can’t dodge!\n Here you go!\n Nice! Kiba, Shikamaru!\n Shikamaru! Let’s get out of here!\n Yeah!\n Punks…!\n You scums… Messing around with us.\n They were full of openings just as I thought.\n Having too much ability individually is also a problem…\n It went well.\n Yeah, it went just as calculated!\n Just in terms of teamwork, ours was way better than theirs.\n I won’t let you get away!\n For the first time, I spoke to you\n And you smiled\n For the first time, I was able to speak\n In my own words\n Would you think it was a bother if I approached you?\n Despite my doubts, I worked up my courage\n My clumsy attempts with words\n You listened without turning away\n No wonder I get carried away by you\n But you don’t feel anything for me, do you?\n I feel so sad\n But…\n For the first time, I spoke to you\n And you smiled\n For the first time, I was able to speak\n In my own words\n For the first time, I spoke to you\n And you smiled\n For the first time, I was able to speak\n In my own words\n For the first time, I spoke to you\n Damn it! To come this far and have another one appear!\n On top of that, there’s something out of ordinary about this guy.\n What’s this bloodcurdling feeling on my back?\n Indeed, we are even on numbers, two against two.\n But this…\n I’m sorry, Naruto. He’s my miscalculation.\n Next episode: “Miscalculation: A New Enemy Appears!”\n"

In [9]:
sentences = sent_tokenize(sample_script)

In [10]:
sentences = sentences[60:90]

In [11]:
sentence = ".".join(sentences)

In [12]:
sentence

'Lord Orochimaru…\n Several bodies have been prepared for you!.And…you could even use me, if necessary…\n It has to be Sasuke…\n How long do you think I’ve waited?.It’s a matter of urgency!.The Third Hokage’s Jutsu…\n His curse was stronger than expected!.Take this!.Sealing Jutsu!.Reaper Death Seal!.Wh-What’s this sensation?.Seal!.My arm…\n If you don’t “reanimate” right now, you’ll lose everything!.Is that what you want?!.Lose everything…\n I’ve selected and prepared proficient bodies for you..Please leave it to me!.Also…\n I’ll handle the recovery of Sasuke as well..Shall I use Kimimaro?.Curse you …\n Third Hokage!.Release!.Listen well, everyone!.I shall release you from this prison…\n However, it’ll only be one of you!.Now all that’s left is to wake up Kimimaro, huh?.Just as I thought…\n I wasn’t summoned this time, either..Dr. Kabuto, I…\n Take care of your body..Your role is now finished..It’s not Sound Ninja Five now, Kimimaro…\n I…still haven’t…\n Your replacement has already been found..He possesses power equal to your “Earth” Curse Mark..He has been given the “Heaven” Curse Mark..Additionally, he even has the Kekkei Genkai..Wonder who’s stronger…\n What’s the matter?.Don’t get too excited..Dr. Kabuto…\n M-My life, how much do I have left?'

# Run Model

In [13]:
doc = nlp_model(sentence)

In [14]:
doc.ents

(Orochimaru,
 Sasuke,
 Third,
 Sasuke,
 Third,
 one,
 Kimimaro,
 Kabuto,
 Kimimaro,
 Kabuto)

In [15]:
for entity in doc.ents:
    print(entity, entity.label_)

Orochimaru PERSON
Sasuke PERSON
Third ORDINAL
Sasuke PERSON
Third ORDINAL
one CARDINAL
Kimimaro PERSON
Kabuto PERSON
Kimimaro PERSON
Kabuto PERSON

In [16]:
def get_ners_inference(script):
    script_sentences = sent_tokenize(script)

    ner_output = []

    for sentence in script_sentences:
        doc = nlp_model(sentence)
        ners = set()
        for entity in doc.ents:
            if entity.label_ =="PERSON":
                full_name = entity.text
                first_name = entity.text.split(" ")[0]
                first_name = first_name.strip()
                ners.add(first_name)
        ner_output.append(ners)

    return ner_output

In [17]:
df = df.head(10)

In [18]:
df

   episode                                             script
0      118  Connecting old words that have been used up\n ...
1      112  Connecting old words that have been used up\n ...
2       24  C'mon!\n Running like a fugitive,\n Being chas...
3      148  Hey boys, listen up!\n Humans aren’t such a bi...
4      123  Connecting old words that have been used up\n ...
5      121  Connecting old words that have been used up\n ...
6      180  Rock away your existence,\n Shouting that you ...
7      160  I want to try and gather the unrestrained wind...
8      168  I want to try and gather the unrestrained wind...
9      190  Rock away your existence,\n Shouting that you ...

In [19]:
df['ners'] = df['script'].apply(get_ners_inference)

In [20]:
df

,episode,script,ners
0,118,Connecting old words that have been used up\n ...,"[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
1,112,Connecting old words that have been used up\n ...,"[{}, {}, {}, {}, {}, {Sasuke}, {Naruto}, {}, {..."
2,24,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {Ibiki}, {}, {}, {}, {}, {}, {}, ..."
3,148,"Hey boys, listen up!\n Humans aren’t such a bi...","[{}, {}, {}, {}, {}, {Tsunade}, {}, {Hinata, K..."
4,123,Connecting old words that have been used up\n ...,"[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
5,121,Connecting old words that have been used up\n ...,"[{}, {}, {}, {}, {}, {}, {}, {Akamaru}, {}, {}..."
6,180,"Rock away your existence,\n Shouting that you ...","[{}, {}, {}, {}, {}, {Natsuhiboshi}, {}, {}, {..."
7,160,I want to try and gather the unrestrained wind...,"[{}, {}, {}, {}, {}, {Tokichi}, {}, {Hinata}, ..."
8,168,I want to try and gather the unrestrained wind...,"[{}, {}, {}, {}, {}, {}, {}, {Ramen}, {Ramen},..."
9,190,"Rock away your existence,\n Shouting that you ...","[{}, {}, {}, {}, {}, {}, {}, {Naruto}, {}, {},..."

In [23]:
dictionary = {"Sasuke"}
dict_list = list(dictionary)
dict_list

['Sasuke']

# Character Network

In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
from pyvis.network import Network

In [ ]:
def generate_character_network(df):

    windows=10
    entity_relationship = []

    for row in df['ners']:
        previous_entities_in_window = []

        for sentence in row:
            previous_entities_in_window.append(list(sentence))
            previous_entities_in_window = previous_entities_in_window[-windows:]

            # Flatten 2D List into 1D List
            previous_entities_flattened = sum(previous_entities_in_window, [])

            for entity in sentence:
                for entity_in_window in previous_entities_flattened:
                    if entity != entity_in_window:
                        entity_relationship.append(sorted([entity, entity_in_window]))
    
    relationship_df = pd.DataFrame({'value': entity_relationship})
    relationship_df['source'] = relationship_df['value'].apply(lambda x: x[0])
    relationship_df['target'] = relationship_df['value'].apply(lambda x: x[1])
    relationship_df = relationship_df.groupby(['source', 'target']).count().reset_index()
    relationship_df = relationship_df.sort_values('value', ascending=False)

    return relationship_df

In [25]:
relationship_df = generate_character_network(df)

In [26]:
relationship_df

         source  target  value
170      Hinata  Naruto     98
287      Naruto  Sasuke     32
94        Choji  Naruto     21
319  Orochimaru  Sasuke     20
88        Choji  Hinata     19
..          ...     ...    ...
253         Lee  Naruto      1
114      Chunin  Naruto      1
113      Chunin     Lee      1
257         Lee   Roger      1
365     Tsunade       –      1

[366 rows x 3 columns]

In [27]:
relationship_df = relationship_df.sort_values('value', ascending=False)
relationship_df = relationship_df.head(200)

In [28]:
G = nx.from_pandas_edgelist(
    relationship_df, 
    source='source', 
    target='target', 
    edge_attr='value',
    create_using=nx.Graph()
)

net = Network(notebook=True, width="1000px", height="700px", bgcolor="#222222", font_color="white", cdn_resources="remote")
node_degree = dict(G.degree)

nx.set_node_attributes(G, node_degree, 'size')
net.from_nx(G)
net.show("naruto.html")

naruto.html